### ISSUE TITLE
Runtime Constraint Generation

### ISSUE THREAD

**Issue by AlexCuse** [netceteragroup/valdr-dotnet#2]
Thanks for all the work on this project.  I was thrilled to find valdr, and even more thrilled to find this package to generate constraints off of DataAnnotations.  I was trying to run the tool to generate constraints as a build step, but ran into issues with assembly loading (asp.net 5 project - the .net core assemblies are splattered all over the place).  What I actually wanted was to generate constraints at runtime, so I ended up moving the parser into my own code to see if it would work (it did).  Is there any interest in making the parser available as a separate package to support this kind of scenario?  

I also noticed that putting the DataContract attribute on my DTOs caused problems for model binding (I essentially got an empty model, no matter what I sent across the wire).  Suspect this is JSON.net behavior but I didn't look into it further.  My implementation will use a different attribute, [ValdrType("Desired Constraint Name")] or similar, to avoid introducing a dependency on System.Runtime.Serialization.

If there is interest in publishing the parser / attribute separately on your end I can fork the repo and send a pull request.  If not I will probably just publish my own package, borrowing heavily from what you've done here.  Let me know how you'd like to proceed.

**Comment by marcelstoer** [comment]
Kai, as https://github.com/netceteragroup/valdr-bean-validation/ has got a [Servlet](https://github.com/netceteragroup/valdr-bean-validation/#servlet) for runtime constraint generation I suggest you add a suitable .NET equivalent here to keep the two libraries in sync feature-wise.

Of course, the Servlet is merely a (web) entry point to the parser and provides very little functionality on top of that. What I consider essential is [CORS](http://en.wikipedia.org/wiki/Cross-origin_resource_sharing) support and a [config option for the allow-origin HTTP header](https://github.com/netceteragroup/valdr-bean-validation/blob/master/valdr-bean-validation-demo/src/main/resources/valdr-bean-validation.json#L6).

**Comment by AlexCuse** [comment]
This should be even easier - I planned to leave the web stuff to the
consumer so there's no need to worry about differences with MVC 5 vs 6
controller implementations.  It'd also leave the door open to using the
parser in an http handler (or a Windows service for all I care).  Would
make it easier to build a command line tool with "dotnet core" support as
well.

I will send a PR later today.  Thanks for the quick response!

**Comment by ilbertz** [comment]
Thanks a lot for the nice pull request and the improvements. This looks fine.

It would be nice if you could describe how to use the new Core NuGet package in the readme, because those pages are linked together.

**Comment by AlexCuse** [comment]
I updated the readme.  Forgot about the problem I ran into with my initial constraint implementation (passed parameters on the constructor instead of as named arguments).  It will be good to have that documented for sure.

Let me know if there's anything else I can do to help.

**Comment by ilbertz** [comment]
Thanks a lot!
