### ISSUE TITLE
Explain version dependency to valdr

### ISSUE THREAD

**Issue by marcelstoer** [netceteragroup/valdr-dotnet#4]
Please explain the version scheme you use in `README.md`. I think it's important your users understand which valdr version works with which version of this lib.

Not sure if you intent to follow the same scheme as valdr Bean Validation but for reference it's explained here: https://github.com/netceteragroup/valdr-bean-validation#dependency-on-valdr

**Comment by ilbertz** [comment]
We follow the same version scheme as valdr Bean Validation now.
